### ISSUE TITLE
refresh the collection causes the folding of the tree

### ISSUE THREAD

**Issue by johaven** [SirIdeas/sirAccordion#1]
This is unfortunate because the tree is really nice.
But if we refresh with dynamic data, the current position is lost.

**Comment by axul** [comment]
Hi @yoyoprs  first of all thanks for your feefback!. You're right, it does actually just re run the whole thing as you can see in the $watch causing the accordion to reset to the initial state. I didn't  think in the possibility of maintaining the current state when updating the collection. But definetively that's a must have option for the directive and we will work on it

**Comment by johaven** [comment]
The $ watch provides the old and the new value of scope.collection; I think it would be possible to merge the old and the new collection and adds the difference. I am currently looking to update dynamically my collections.
To conserve current index, store it in var and try to refind the location after the refresh no ?

**Comment by axul** [comment]
Yep that's how we'll do it. the problem would be after that updating the dom and mainting the previous state of the tree but that should be doable.

**Comment by johaven** [comment]
Yes this means you can remove and add items dynamically but it would be a great feature. Currently I use it to browse a file tree :)
