### ISSUE TITLE
On click event and UI state route change

### ISSUE THREAD

**Issue by warapitiya** [SirIdeas/sirAccordion#4]
If this module can support "on click" event and "UI router" state change would added advantage.

**Comment by axul** [comment]
Hi @warapitiya, If you like you can attach an event with js or jquery to handle it by yourself, I didn't want to make the accordion too complicated. For example I have this code to scroll to an element when I click on an accordion header `$('.sir-accordion-header').on('click', function(e) { var offset = document.getElementById('accordion-cuerpo').scrollTop;$(this).velocity('scroll', { offset: -offset, container: $('#accordion-cuerpo'), duration: 400, delay: 400});});`.

As for the UI router support, maybe you can tell me what are you trying to acheive and I'll look if I can do something with UI router

**Comment by axul** [comment]
I'm closing this issue, I think  the click or any event that is not core of the accordion, should be handled in a js standard way by the developer as in the example above.
