### ISSUE TITLE
Calling functions from contents with ng-click

### ISSUE THREAD

**Issue by siemya** [SirIdeas/sirAccordion#6]
Hey,
How can i add ng-click events to my contents to call functions.

**Comment by axul** [comment]
Hi, I actually Fixed that problem in the dev branch, since it was kind of messy to do. I'll be merging changes and releasing the next version in witch you can use ng-click like you would on any template tomorrow. Sorry for taking too long to reply. I missed the notification somehow

**Comment by NevillePHolistics** [comment]
Hi, have you managed to do this yet? If so, can you kindly give a small example of how to implement a ng-click on one of the accordion node's content?

**Comment by axul** [comment]
@NevillePHolistics Hi! Actually no, sorry, is still in the dev branch, I've been focusing in other projects for now, I'll try to do it soon. Its kinda dumb that this function wasn't there from the start. A workaround (that I'm currently using) to have interaction in an element inside of the contents is to use a directive, then you can add `element.on('click', function());`

**Comment by axul** [comment]
This is now currently done in the latest commit in the master branch. Awaiting for documentation for the next release

**Comment by NevillePHolistics** [comment]
Cool but I'm can't really remember what I needed it for anymore. I'll try it out though as soon as there is some documentation. Thanks!

**Comment by axul** [comment]
Ok its done now, closing the issue
